ALTER TABLE public."User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ClientApproval" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ServicePackage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Booking" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."BookingReminder" ENABLE ROW LEVEL SECURITY;;
