ALTER TABLE public."StaffAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ProjectTask" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ProjectNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ClientCommunication" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."_prisma_migrations" ENABLE ROW LEVEL SECURITY;;
