CREATE TYPE "DeliveryDeadline" AS ENUM ('STANDARD', 'EXPRESS', 'URGENT');
CREATE TYPE "BookingStatusV2" AS ENUM ('INQUIRY','QUOTATION_SENT','AWAITING_DEPOSIT','CONFIRMED','CREW_ASSIGNED','EQUIPMENT_PREPARED','EVENT_DAY','MEDIA_UPLOADING','EDITING','QUALITY_REVIEW','READY_FOR_DELIVERY','CUSTOMER_NOTIFIED','DELIVERED','COMPLETED','ARCHIVED','CANCELLED');;
